graph TD
    A[Raiz del proyecto] --> B[src]
    B --> C[aeroalpes]
    C --> C1[api]
    C --> C2[config]
    C --> C3[ejemplos]
    C --> C4[seedwork]
    C --> C5[modulos]
    C5 --> D1[cliente]
    C5 --> D2[hoteles]
    C5 --> D3[pagos]
    C5 --> D4[precios_dinamicos]
    C5 --> D5[vehiculos]
    C5 --> D6[vuelos]
    A --> E[tests]
